name: service
partOf: subsystem

env:
  JDK_JAVA_OPTIONS: >-
    -XX:ActiveProcessorCount=2
    -XX:MaxRAMPercentage=75
    -XX:+UseParallelGC
    -Duser.timezone=UTC
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: 10s

service:
  enabled: true

pod:
  terminationGracePeriodSeconds: 15

container:
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  livenessProbe:
    initialDelaySeconds: 70
    timeoutSeconds: 1
    periodSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 1
    periodSeconds: 5
    failureThreshold: 3

ingress:
  enabled: true
  hosts:
    - host: service.local
      paths:
        - path: /
          pathType: Prefix
